---

- name: "Install requirements"
  import_tasks: requirements.yml

- name: Install NodeJS
  import_tasks: nodejs/main.yml

- name: Build and Install ODBC Connector
  import_tasks: mariadb-odbc/main.yml

- name: Build and Install Asterisk
  import_tasks: asterisk/main.yml

- name: Create database
  import_tasks: createdb.yml

- name: Setup ODBC Connector
  import_tasks: configure_odbc.yml

- name: Configure Apache2 and Asterisk Users and Groups
  import_tasks: install_main.yml

- name: Install FreePBX
  import_tasks: freepbx/main.yml

- name: Install custom modules
  import_tasks: freepbx/install_extra_modules.yml
  when: freepbx_install_extra_modules
